### ISSUE TITLE
Type errors for keyword argument aliases

### ISSUE THREAD

**Issue by julianwieg** [rabobank-cdc/DeTTACT#2]
Python Noob here, (sorry)

I tried and "think" I setup python correctly with all dependencies (using pip) on Windows 10 and Ubuntu but on both I always get the following error when trying to run dettact.py

Any help would be appreciated.  If this is not an issue with the scripts/code and a python error please close the issue but I am really unsure.

Thank you
```
Traceback (most recent call last):
  File "dettact.py", line 202, in <module>
    menu(init_menu())
  File "dettact.py", line 27, in init_menu
    description='Create a heat map based on data sources, output data '
  File "C:\Python27\lib\argparse.py", line 1066, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases'
```

**Comment by rubinatorz** [comment]
Hi @julianwieg 

I guess you are using python2.x, which is not supporting the aliases keyword in argparse library. Please try python3.x (install libraries again for python3).

Please let us know if that solves your problem.

Cheers

**Comment by julianwieg** [comment]
Thank you works.  
My excuse is that I was using a VM (windows) where I did not know I had python 2 installed... I did download and install python 3 but was not using it obviously  👍
