### ISSUE TITLE
Product List Not Appending For Visibility ATT&CK Layer

### ISSUE THREAD

**Issue by tuckner** [rabobank-cdc/DeTTACT#3]
I am finding that when generated an ATT&CK layer for visibility, when there are multiple data sources capable of detecting a technique, only the last data source's "Products" are being shown when I believe it should be appended to provide a full list of Products giving visibility.

**Comment by marcusbakker** [comment]
Hi Tuckner,

Thanks for reporting this bug! It should be fixed now.

Regards,
Marcus

**Comment by tuckner** [comment]
Thank you so much!
